### ISSUE TITLE
Features to add to gaussian bayeschime

### ISSUE THREAD

**Issue by cranedroesch** [pennsignals/chime_sims#61]
-  Flexible beta IN PROGRESS
   To test:
   - All the hospitals
   - Holdout sets
   - nonlinear spline bases (powers to start)
-  Cross-validation IN PROGRESS
- Output of plots of beta, maybe R too 
-  Make it so that the output doesn't necessarily dump to a new folder.  Create a python api
- Mobility as an input to beta
- Flexible LOS
- Case count as an input and output
- Modify burnin removal to make it configurable DONE
- Diagnostic checks on posterior trace, maybe automatic burnin removal
- Integrate chain munging into main script so that it's not necessary to rely on the pipes

**Comment by DougManuel** [comment]
Just a big thanks. There is a lot in this issue that is on our wish list up in Ottawa. And yes, Rt.

We appreciate your repo!

**Comment by cranedroesch** [comment]
Closing for staleness
