### ISSUE TITLE
Broken reopen_cap parameter

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime_sims#66]
reopen_cap parameter isn't explicitly passed into the sir function.  So the default value of 0.50 is always used.

Minor issue the reopen_cap parameter is 
```line 660:     plt.title(f"Reopening scenario, {int(reopen_speed*100)}% per day up to {int(reopen_speed*100)}% social distancing")```
Should be updated to 
```line 660:     plt.title(f"Reopening scenario, {int(reopen_speed*100)}% per day up to {int(reopen_cap*100)}% social distancing")```

My workaround. I just changed the sir default from 0.5 to 0.3.

**Comment by cranedroesch** [comment]
I fixed this on Friday evening with 1a0a8201e4b344a66522bd00731c74a78596f485.
