### ISSUE TITLE
 RuntimeWarning: overflow encountered in exp

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime_sims#68]
Unexpected overflow warnings 

/chime_sims/_99_shared_functions.py:134: RuntimeWarning: overflow encountered in exp

and 

/home/datascience/miked/chime_sims/_02_munge_chains.py:15: RuntimeWarning: overflow encountered in exp

**Comment by cjbayesian** [comment]
@Mdraugelis These warnings happened when running the `master` branch, correct?

**Comment by cjbayesian** [comment]
First overflow is happening in:
```python
def logistic(L, k, x0, x):
    return L / (1 + np.exp(-k * (x - x0)))
```

**Comment by cjbayesian** [comment]
`np.exp` will overflow for arguments ~> 710.0 on a 64 bit architecture (max floating point values ~ 8.218407461554972e+307). This results in the runtime warning you're seeing:

```python
In [9]: np.exp(1000)                                                                                                                                          
/home/datascience/anaconda3/bin/ipython:1: RuntimeWarning: overflow encountered in exp
  #!/home/datascience/anaconda3/bin/python
Out[9]: inf
```

However, when this happens, the logistic function returns `0.0` as `(float(x)/np.inf) == 0.0`:

```python
In [12]: logistic(10, 1000, 1, 0)                                                                                                                             
/home/datascience/anaconda3/bin/ipython:2: RuntimeWarning: overflow encountered in exp
  
Out[12]: 0.0
```

Therefore, this overflow can happen and nevertheless yield a valid likelihood value.

**Comment by cjbayesian** [comment]
We may want to catch that overflow explicitly and have `logistic` return `np.nan` so that those regions of the parameter space are explicitly rejected.

**Comment by Mdraugelis** [comment]
got it. thanks for investigating.  And I ran this on acd_dev.  I should have noted that.  I did not see this warning on the master.
