### ISSUE TITLE
reopen_cap parameter isn't working

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime_sims#72]
I've run with parameter of reopening at 0% and 20% which results in the same output.  My guess is the default of 100% is being used.

This was run with the latest master branch. Outputs can be found on ```datascience@use2-uphs-pennsignals-ds-compute-01:~/miked/chime_sims```

# Run we cap at zero

I expect to see no covid resurgence with 0%

```
{"my_config": null, "prefix": "CCH", "parameters": "data/CCH_parameters.csv", 
"ts": "data/CCH_ts.csv", "n_chains": 8, "n_iters": 5000, "fit_penalty": false, "penalty": 0.25,
 "sample_obs": false, "out": "CCH_flexB_novent", "as_of": 0, "flexible_beta": true, 
"verbose": false, "burn_in": 2000, "n_days": null, "y_max": null, "plot_pairs": true, 
"reopen_day": 100, "reopen_speed": 0.05, "reopen_cap": 0.0, "forecast_change_prior_mean": 0,
 "forecast_change_prior_sd": -9999.9, "save_chains": false, "ignore_vent": true}
```

![image](https://user-images.githubusercontent.com/525828/82682541-69215c00-9c1d-11ea-8a1b-a13c209af623.png)

# Run we cap at 20%

![image](https://user-images.githubusercontent.com/525828/82682843-e4830d80-9c1d-11ea-9d7c-6020ba5badf6.png)

![image](https://user-images.githubusercontent.com/525828/82682777-ccab8980-9c1d-11ea-94e0-8a8fbf484334.png)

**Comment by cranedroesch** [comment]
This got fixed in the merge above
